export const DataUser = [
  {
    id: "1",
    username: "Test",
    password: "Test",
    email: "Test@Test.com",
    name: "Test",
    surname: "Test",
    phone: "+48 123 321 123",
    pack: "Test",
    group: "Test",
    condition: "Test",
    status: "Test",
    dateRegister: "12.21.21",
    role: "user",
  },
  {
    id: "2",
    username: "Test2",
    password: "Test2",
    email: "Test@Test.com",
    name: "Test2",
    surname: "Test2",
    phone: "+48 123 321 123",
    pack: "Test",
    group: "Test",
    condition: "Test",
    status: "Test",
    dateRegister: "12.21.21",
    role: "admin",
  },
];